### PYTHON LIBRARIES
#### NUMPY
- Numpy (Numerical Python)
- It creates arrays bcoz arrays are faster than list
- created in 2005 by Travis Oliphant
- To create multi-dimentinol Arrays we use numpy


In [7]:
#### Create 1D Array
import numpy as np
y=numpy.array([1,2,3,4])
print(y)

[1 2 3 4]


In [8]:
ol=np.array([1,2,3,4])
print(ol)

[1 2 3 4]


In [9]:
print(type(y))

<class 'numpy.ndarray'>


In [11]:
# create 2D Array
x=np.array([[1,10,20,22,29],[92,22,2,1,0]])
print(x)

[[ 1 10 20 22 29]
 [92 22  2  1  0]]


In [17]:
#create 3D Array
z=np.array([[1,10,20,22,29],[92,22,2,1,0],[1,2,3,4,5]])
print(z)
print(z.ndim)# to know the dimention of an array
print(z.shape)# to know the No of columns and rows
print(z.size)# to know the number of elements 

[[ 1 10 20 22 29]
 [92 22  2  1  0]
 [ 1  2  3  4  5]]
2
(3, 5)
15


In [14]:
#Method 2
a=[[1,10,20,22,29],[92,22,2,1,0]]
b=np.array(a)
print(b)
print(b[0][1])

[[ 1 10 20 22 29]
 [92 22  2  1  0]]
10


In [18]:
o=np.array([1,2,3,4,5,6,7,8,9],ndmin=3)
print(o)

[[[1 2 3 4 5 6 7 8 9]]]


In [19]:
p=np.array([1,29,35], dtype=complex)
print(p)

[ 1.+0.j 29.+0.j 35.+0.j]


In [30]:
#Slicing
x=np.arange(10)
print(x)
x
print(x[0:5])
print(x[-5:])
print(x[::2])
print(x[::-1])
print(x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[0 2 4 6 8]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [32]:
n=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(n)
print(n.size)
print(n.shape)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
12
(2, 2, 3)


## Reshaping of Arrays

In [43]:
s=np.arange(1,13).reshape((3,4))
print(s)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [48]:
### concatenation of arrays
x1=np.array([1,2,3])
y1=np.array([4,5,6])
z1=np.concatenate([x1,y1])
print(z1)

[1 2 3 4 5 6]


In [50]:
z1[2]+z1[5]

9

In [53]:
#### Splitting of Arrays
x=[1,2,3,4,5,6,7,8,9]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 7 8 9]


In [56]:
t=np.arange(1,17).reshape((4,4))
print(t)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [58]:
a1=np.arange(1010)
a1

array([   0,    1,    2, ..., 1007, 1008, 1009])

In [60]:
a2=np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [64]:
a4=np.arange(12).reshape(6,2)
print(a4)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [65]:
sp=np.ones((3,3))
print(sp)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [69]:
s2=sp+2
print(s2)
s3=s2*2
print(s3)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [74]:
a=[1,2,3]
a1=np.array(a)
print(a1)
print(np.sqrt(a1))
print(np.sin(a1))
print(np.cos(a1))
print(np.log(a1))
x=np.random.rand(2,5)
print(x)

[1 2 3]
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
[[0.73199275 0.56375098 0.10117326 0.34347116 0.59984739]
 [0.07242284 0.46918656 0.01952476 0.67265545 0.57079128]]


In [85]:
a=np.random.randint(3,size=10)
print(a)

[2 2 1 0 0 2 1 2 2 1]


In [84]:
a1=np.random.randint(3,size=10)
print(a1)

[0 2 0 2 0 0 0 2 0 0]


In [88]:
print(len(dir(np)))

620


In [90]:
print(np.__version__)

1.19.2


In [92]:
### FILTERING Arrays
ary=np.array([11,12,13,14,15])
x=[True,False,True,False,True]
nary=ary[x]
print(nary)

[11 13 15]


In [96]:
ar=np.array([1,2,3,4,5,6])
filter_ar=ar%2==0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[False  True False  True False  True]
[2 4 6]


In [97]:
ar=np.array([1,2,3,4,5,6])
filter_ar=ar%2!=0
new_ar=ar[filter_ar]
print(filter_ar)
print(new_ar)

[ True False  True False  True False]
[1 3 5]


In [104]:
#### Statistical Arrays
a=np.array([[1,10,20,22,29],[92,22,2,1,0],[1,2,3,4,5]])
print(a)
print(np.amax(a,1))
print(np.amin(a,1))

[[ 1 10 20 22 29]
 [92 22  2  1  0]
 [ 1  2  3  4  5]]
[29 92  5]
[1 0 1]
